CMakeLists.txt

cmake didn't work out of the box with v0.5, so I played around with it a little bit (and
learned more about cmake than I ever wanted :-)
This PR fixes building with cmake; I made -O3 the default optimization; also, AVX2
is enabled by default, but can be disabled with `cmake -DENABLE_AVX=0`.

Fix cmake build

---

CMakeLists.txt

Not sure why this didnt happen before, but 0.7 failed to build for me when trying
to link the final executable:
```
[100%] Linking CXX executable strobealign
/usr/bin/ld: CMakeFiles/strobealign.dir/main.cpp.o: in function `main':
main.cpp:(.text.startup+0x1f95): undefined reference to `pthread_create'
/usr/bin/ld: main.cpp:(.text.startup+0x2618): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/strobealign.dir/build.make:190: strobealign] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/strobealign.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
This PR adds pthread detection and corresponding link flags to the cmake build.

cmake build: add pthreads

---

main.cpp

Minor changes:
* make sure reference file can be read
* test if it starts with a '>' character
* abort run if no reference sequences could be read

add basic checks for reference file (#28)

---

src/main.cpp

This extracts a `parse_command_line_arguments` function from `main()`. All parameters are stored in a new `CommandLineOptions` struct that is returned from that function. This needs a bit more work, but I thought it’s a good enough improvement to be worth a PR already now. It may be a good idea to use an external command-line parsing library (which would also automatically generate a help text), but that’s for later.
This PR also adds a `-h` command-line option that prints the help and exits with an exit code signaling success. This is helpful in the Conda recipe (and I think generally best practice), which needs to run a simple command that just ensures that the binary can be executed.
*Edit:* I noticed only now that `strobealign` doesn’t properly set an exit code when there was a …

Move command-line handling to separate function and add `-h` (help)

---

src/main.cpp

See https://stackoverflow.com/questions/748014/

No need to call .close() manually - the destructor does it

---

CMakeLists.txt

We cannot rely on AVX2 instructions being supported by the target CPU, so
it’s better to disable it by default and let the user enable it explicitly.
Automatic CPU detection would be even nicer.
Closes #34

Disable AVX2 support by default

---

ext/README.md
ext/args.hxx
src/main.cpp

This library is available from https://github.com/Taywee/args/
This eliminates lots of error-prone parsing code, gives us nicer error messages, auto-generated help and some other features.
There are some alternatives that are probably more powerful, such as TCLAP http://tclap.sourceforge.net/ and boost::program_options::basic_command_line_parser, but args is good enough and only requires copying a single header file into our ext/ directory.
The help output doesn’t look exactly as before, but we can tune that later if we find it necessary. It looks like this now:
```
strobealign reference reads1 [reads2] {OPTIONS}
StrobeAlign 0.7.1
OPTIONS:
-h, --help    Print help and exit
-t [threads], --threads=[threads]
Number of threads [3]
Input/output:
-o [STR]      redirect output to file [stdout] …
```

Rewrite command-line parsing to use the external "args" library

---

CMakeLists.txt
src/main.cpp
src/version.hpp.in

With this, CMake generates a version.hpp containing the version number set in `CMakeLists.txt`. The `version.hpp` file is included from `main.cpp`.
To update the version number in the future, only `CMakeLists.txt` needs to be changed.

Maintain version number in only one place

---

src/index.cpp
src/index.hpp
src/main.cpp

This contains a couple of changes only related by the fact that I did them while trying to understand some functions.
Quite a few functions in strobealign use function arguments not only for passing in parameters, but also for returning values (passed by reference). This makes it a bit hard to understand what’s going on. Some functions even take multiple parameters that are passed by reference, but some of them are inputs and some of them are outputs. At the call site, one cannot see which parameters are modified and which aren’t. One improvement is to mark the inputs as `const`, which I’ve done here in some places.

Add const to some function calls (and refactor process_flat_vector)

---

src/aln.cpp
src/aln.hpp

This makes the intention clearer, the code shorter and avoids repeating expressions.
This isn’t complete; I got to about line 1800 in aln.cpp.

Use std::{max,min,abs} instead of ternary operators

---

src/aln.cpp
src/sam.cpp
src/sam.hpp

Two changes:
* Change some functions that have separate parameters for sequence, name and qualities to have a KSeq parameter instead
* Add lots of `const`s to help document which parameters are "in" parameters

Consts and use KSeq

---

src/cmdline.cpp
src/cmdline.hpp
src/index.cpp
src/logger.hpp
src/main.cpp

I think the log output is a bit "intimidating" and contains some lines that an end user doesn’t need to see. This PR silences some of these messages by default and adds a command-line option `-v` (verbose) that can be used to re-enable them.
This is achieved by introducing a very simple `Logger` class. Instead of writing to `std::cerr` unconditionally, each message is written to `logger.debug()` or `logger.info()` (`logger.warning()` and `logger.error()` are also available). Only messages at least as high as the current log level are printed, and the default log level is set to `LOG_INFO`. The `-v` option sets the current log level to `LOG_DEBUG`. We could also add a `--quiet` option later that would set the log level to `LOG_WARNING` and therefore hide even the info-level messages.

Less verbose default logging output

---

CMakeLists.txt
src/aln.cpp
src/aln.hpp
src/fasta.cpp
src/fasta.hpp
src/index.cpp
src/index.hpp
src/main.cpp
src/pc.cpp
src/pc.hpp
src/refs.cpp
src/refs.hpp
src/sam.cpp
src/sam.hpp
tests/tests.cpp

A `References` instance stores the sequences read from a FASTA file. It has fields for the sequences, their names and their lengths. Instead of separately passing sequnce names and lengths to functions, this allows us to pass a single `references` object.
* `read_references` is now the static method `References::from_fasta` that returns a `References` instance.
* Moved sequences, names and lengths out of `st_index`. Instead, the `write_index`/`read_index` functions get a `References` object as additional parameter.
* Get rid of `total_ref_seq_size`. Instead, total reference size is computed within the `References` constructor and can be retrieved with the `total_length()` method.

Add a References class

---

src/aln.cpp

The diff may be hard to read, but this just transforms this
```c
void f() {
if (a) {
// lots of lines
}
}
```
into
```c
void f() {
if (!a) {
return;
}
// same lines as above, but de-dented one level
}
```
The idea is to get the special cases out of the way early on to be able to focus on the "meat" of the function after that.

Use early return in a function to be able to de-dent the other lines

---

src/aln.cpp

See https://graphics.stanford.edu/~seander/bithacks.html#IntegerMinOrMax for where these hacks come from. GCC actually recognizes these and replaces them with the same code that is produced by using std::min/max, which uses conditional move instructions (which are branchless).
See https://godbolt.org/z/KPWKdfjT9

Avoid bit-fiddling hacks for computing min/max

---

.github/workflows/ci.yml
src/cmdline.cpp

... and fix one occurrence. This adds a simple linting job to the Actions workflow, which should help us avoid usage of mixed tabs and spaces for indentation.

Ensure no tab characters are present in sources

---

src/aln.cpp
src/aln.hpp
src/index.hpp
src/main.cpp
src/pc.cpp
src/pc.hpp
src/refs.hpp
src/sam.cpp
src/sam.hpp

Instead of passing reference lengths/names/sequences as separate parameters, pass a "References" object into various functions.

Pass "References" objects when appropriate

---

src/aln.cpp
src/aln.hpp
src/index.hpp
src/main.cpp
src/pc.cpp
src/pc.hpp

Only by inspecting the code became it clear to me that the values stored in `logging_vars` are actually only for the alignment stage. Renaming it to `AlignmentStatistics` makes this clearer. Also, move the struct to `aln.hpp` because that is the right place (it doesn’t have anything to do with index creation).

Move logging_variables to aln.hpp and rename to AlignmentStatistics

---

src/aln.cpp
src/index.cpp
src/index.hpp
src/main.cpp
src/randstrobes.cpp
src/randstrobes.hpp

Accessing tuple fields with `std::get<index>` is error prone and not so readable, so this replaces many tuples with proper structs that have named fields.
* `MersIndexEntry`: an element of `flat_vector` (with fields hash, position, packed)
* `KmerLookupEntry`: an element of `kmer_lookup`
, `QueryMer`: an element of `mers_vector_read`
* `Hit`
I’m not so happy with the names of the structs, yet. In particular, `Hit` collides a bit with the lowercase `hit` struct in `index.hpp`, but I think this is an improvement already and finding better names can be done in a separate step.

Add some structs to replace tuples

---

src/aln.cpp
src/index.cpp
src/main.cpp

and use std::{max,min,abs} instead.
The remaining usages of the ternary operator are either less easily replaced or are readable.
See #57, this finishes what was begun there.

Reduce usage of ternary operators

---

src/aln.cpp
src/sam.cpp
src/sam.hpp

This avoids double negations. For example, `!sam_aln1.not_proper` now reads as `sam_aln1.is_proper`.

Rename alignment::not_proper to is_proper and invert meaning

---

src/aln.cpp
src/aln.hpp
src/cmdline.cpp
src/cmdline.hpp
src/exceptions.hpp
src/index.cpp
src/index.hpp
src/main.cpp
src/pc.cpp
src/pc.hpp
src/randstrobes.cpp
src/randstrobes.hpp

Hopefully no logic changes, only refactoring.
- Pass `StrobemerIndex` to functions instead of two separate `kmer_lookup` and `mers_vector` objects. This cleans up some functions signatures nicely.
- Added a `IndexParameters` struct for all parameters that influence index creation.
- Move some parameters from `mapping_params` into `IndexParameters` (not all, yet)
- Make more parameters `const`
Adding the `IndexParameters` struct increases again the number of parameters for some functions, but I actually want to move the indexing parameters directly into the StrobemerIndex, and then the extra parameters disappear once more. I’m not sure whether that is actually possible, but in any case, I find it helpful to have index parameters in a different place than mapping parameters because we could …

Refactor index

---

src/aln.cpp
src/aln.hpp
src/cmdline.cpp
src/cmdline.hpp
src/index.cpp
src/index.hpp
src/main.cpp

- `index.cpp` no longer refers to `mapping_param` anywhere
- Move more mapping_params members into `IndexParameters`

Make indexing independent of mapping_params

---

src/aln.cpp
src/revcomp.hpp

RcRead objects wrap a string and its reverse complement. The reverse complement is only computed on first access and then cached.
With this, the three parameters "read", "read_rc" and "rc_already_comp" that are passed to many functions can be replaced by a single "read".
~~I think I will add another commit to rename RcRead to just Read. Reading a variable `rcread`, it looks as if that already were a reverse-complemented sequence.~~ Done

Factor out a Read class that caches reverse complements

---

src/cmdline.cpp
src/cmdline.hpp
src/exceptions.hpp
src/index.cpp
src/index.hpp
src/main.cpp
tests/run.sh
tests/tests.cpp

- When `-i` is specified, write the index to reference path + `.sti`
- When --use-index is specified, read the index from reference path + `.sti`
- If `-i` is used and one or two reads files are provided, estimate read length from the reads
- Do not write the reference sequences to the index (read them from the FASTA instead)
- Write a "magic number" as the first four bytes to the index file so that we can be somewhat sure that it actually is a strobemer index when reading it in again.
See #115

Turn -i into a flag and add --use-index option

---

CMakeLists.txt
src/exceptions.hpp
src/fastq.cpp
src/fastq.hpp
src/main.cpp
src/pc.hpp
tests/tests.cpp

- Factor out an open_fastq function
- Check whether gzopen() returns nullptr
- Pass "gzclose" to make_ikstream to make it automatically close
the underlying file
This also splits out a `run_strobealign` function from `main()` that does most of the work. `run_strobalign()` only throws exceptions and never exits if there is an error. This makes it easier to use the function in a library.

Properly exit if an input FASTQ file is missing

---

.github/workflows/ci.yml

Run the job for PRs only if they come from a forked repo. From here:
https://wildwolf.name/github-actions-how-to-avoid-running-the-same-workflow-multiple-times/

Avoid running GitHub Actions job twice

---

src/aln.cpp

This splits out code that is duplicated in `get_alignment()`, `rescue_mate()`, `align_SE()` and `align_SE_secondary_hits()` into a separate function and simplifies that function a bit.
I have verified that this gives identical results not only on the small test dataset, but also on a larger test dataset, both in single-end and paired-end mode.
This shrinks `aln.cpp` by 280 lines.

Factor out reverse_nam_if_needed

---

src/aln.cpp

This change was introduced in https://github.com/ksahlin/StrobeAlign/commit/6973009f4779cd54aaa9ae1bc6420ba9aa80d0f3 and leads to reduced accuracy on larger references. It was intended as a refactoring and not meant to change results. The difference in results is not visible on the tiny phiX test dataset.

Fix incorrect refactor in find_nams

---

src/aln.cpp

Used only once and only computes a single-expression: A good candidate for a lambda.

Convert sort_highest_sw_scores_single to a lambda

---

src/refs.cpp
tests/tests.cpp

I found that commit d9872741201396f2ce144e0b0ed0ce15d7ae5ac3, merged as part of PR #55, is responsible for a decrease in accuracy. The issue is that only the last reference in the FASTA file is converted to uppercase. This problem was not caught using the phiX reference because it only contains one sequence. This PR adds more extensive tests, fixes the bug and also fixes another issue where the `names` attribute could have too many entries.
I don’t know, yet, whether this restores accuracy to the level of v0.7.1. I will check that later.

Fix conversion of reference to uppercase

---

.github/workflows/ci.yml
tests/baseline-commit.txt
tests/download.sh
tests/samdiff.py

This adds another GitHub Actions job that tests StrobeAlign on a somewhat bigger dataset. The idea is to compare the SAM/BAM output against a "baseline" commit for which we assume StrobeAlign produces correct results.
The file `tests/baseline_commit.txt` sets this baseline commit. It is currently ef86bce15896b5cca437c54ff95dfad40da2145a, which is the same as the current main. We have established that this version gives us results that are sufficienty close in accuracy to v0.7.1, so this should be a good starting point. Whenever mapping results change on purpose, we need to update the commit hash in that file. I am not super happy with this procedure and would prefer to not have this manual update, but have to think a bit how to improve upon that.
The steps of the GitHub Action are as …

Run tests on a bigger dataset

---

src/aln.cpp
src/sam.cpp
src/sam.hpp
tests/tests.cpp

I attempted to fix this in #151, which led to different mapping results. With my previous change, `Sam::add_pair` would no longer change the `is_proper` attribute for the two alignments that are passed in. At one of the sites where `add_pair()` was called, this was actually relied upon. I have now extracted a function `is_proper_pair()`, which needs to be called to compute whether an alignment pair is a proper pair. This allows us to make the two `alignment` parameters to `Sam::add_pair` const, which was on my to-do list anyway.
Closes #142

Fix: TLEN should be zero when reads map to different contigs 

---

tests/samdiff.py

Example output:
```
Before/after comparisons
19269 times: read was unmapped before and after
*         2 times: read became mapped
*         1 times: read became unmapped
180484 times: read was mapped to same locus before and after
*        89 times: read was multimapper before and after, same alignment score (AS)
*         9 times: read was multimapper before and after, better alignment score (AS)
*       146 times: read changed in another way (shown above if any)
200000 total reads
```
The `*` in the beginning means that the row should be zero, but is not. If there are any `*`, then the script exits with exit code 1 (we want this to make the tests fail).

Try to make samdiff script output a bit better to interpret

---

src/randstrobes.cpp

This has a lot of commits because I went in small steps, running the tests after each.
This doesn’t actually call one function from the other as I had originally intended, but goes a different way.
The main idea is to introduce a `RandstrobeIterator` class that computes the randstrobes. The previous `get_next_strobe_dist_constraint()` function became a method of that class. All its parameters are passed just once to the `RandstrobeIterator` constructor and are stored in the instance, so they do not need to be passed again on the next iteration. Furthermore, the method returns an instance of a new `Randstrobe` struct instead of using non-const reference parameters. Also, the iterator itself now keeps track of where it is in the `string_hashes` list, so that in the end a single `.next()` …

De-duplicate randstrobes functions somewhat

---

CMakeLists.txt
src/main.cpp
src/timer.hpp

This adds the following two lines to the logging output:
```
This is StrobeAlign v0.7.1.0-423-gc5b8545
Estimated read length: 296 bp
```
Also, I converted from direct usage of `std::chrono` to our `Timer` class while I was there.
I think logging could be made a bit nicer in a couple of other ways, but I will open a separate issue about that.

Log the version

---

src/aln.cpp
src/sam.hpp

One of the previous PRs made it superfluous.

Remove alignment::is_proper attribute

---

src/cmdline.cpp
src/cmdline.hpp
src/randstrobes.cpp
tests/run.sh

This PR contains mostly refactoring commits, but the last one 33964c1c9de157a3fd7338712efd4ff117d031b9 is more interesting because it speeds up computation of snycmers a little bit.
I noticed that `make_string_to_hashvalues_open_syncmers_canonical()` keeps track of the s-mer hashes in `qs` and their start positions in `qs_pos`, but the positions can actually be computed when needed. This is possible because `qs_pos` only ever contains consecutive indices (5, 6, 7, etc.).
For mapping 1 million reads from the real Drosophila dataset, overall runtime decreases from ~304 to ~301 seconds (when run with `-t 1`). It appears that the compiler is already quite good at reducing the overhead from using the second `std::deque`, so the benefit isn’t huge. In any case, 1% is better than nothing an …

Slightly faster syncmer computation

---

README.md
src/cmdline.cpp
src/main.cpp

The README is a bit inconsistent in how it spells "StrobeAlign". It often uses all-lowercase "strobealign". This makes the name consistently be "StrobeAlign" in the README.
Lowercase `strobealign` remains when the binary itself is meant.

Consistently use the spelling "strobealign"

---

src/aln.hpp
src/index.cpp
src/index.hpp
src/main.cpp
src/pc.cpp

This revamps the way index creation times are kept track of and logged to make them more consistent and easier to interpret.
```
This is StrobeAlign v0.7.1.0-460-ge79fa3f
Estimated read length: 151 bp
Time reading references: 0.499928 s
Time generating seeds: 2.05037 s
Time sorting seeds: 1.86406 s
Time copying flat vector: 0.125275 s
Total time generating flat vector: 4.06984 s
Total time generating hash table index: 1.30964 s
Total time indexing: 5.38767 s
Running in paired-end mode
```
```
This is StrobeAlign v0.7.1.0-470-g4d250c8
Estimated read length: 151 bp
Time reading references: 0.46 s
Indexing ...
Time generating seeds: 1.99 s
Time sorting seeds: 1.85 s
Time generating flat vector: 0.12 s
Time generating hash table index: 1.31 s
Total time indexing: 5.31 s
Running in paired-end …
```

Log index creation times in a nicer way

---

CHANGES.md
src/aln.cpp
src/cmdline.cpp
src/cmdline.hpp
src/main.cpp
src/pc.cpp
src/pc.hpp
tests/baseline-commit.txt
tests/run.sh

Ensuring correct order is done as discussed in #121: Read chunks are numbered consecutively, and processed chunks are buffered until it is their turn. This could theoretically affect performance a little bit because the lock that protects the output buffer is held a bit longer sometimes, but I wasn’t able to measure a significant difference (it must be less than ~1% if there is a difference).
This PR also reduces the default chunk size from 100'000 to 10'000. Together with ensuring reproducible read order, this finally allows us to run the tests on the somewhat larger dataset with multiple threads.
I also added a command-line option `--chunk-size`, which is hidden from help output. I use it in the tests to set a very low chunk size, which enables multithreading even on the tiny phiX …

Output mapped reads in the order that they had in the input file and decrease default chunk size

---

src/refs.cpp
src/refs.hpp

* Fix an unnecessary copy of the reference sequences. This was introduced when References::from_fasta was factored out. This increased peak memory usage just before creating the index, so it does not matter overall because the memory is immediately freed and then used for the index.
* Speed up uppercasing the reference. Reading a 3 GB reference takes about 1.8 seconds, but converting it to
uppercase with std::toupper takes another 6 seconds because toupper takes the current locale into account. Since we assume ASCII for the FASTA input file anyway, we can use a custom function that manipulates the bits of the
char. This takes only ~0.2 seconds.

Fix: Reference sequences copied unnecessarily, speed up uppercasing

---

.github/workflows/ci.yml
CMakeLists.txt
src/aln.cpp
tests/samdiff.py

This is achieved by manually setting the compiler options for the "RelWithDebInfo" build type (and omitting `-DNDEBUG`).
Also, we need to ensure that we use the bash option `-o pipefail`. Without it, the exit code from `strobealign ... | samtools view ...` is 0 as long as samtools exits successfully even when strobealign crashed.
This also disables some assertions that I added in 97939f3e. I never noticed that they were triggered because I did not have assertions enabled. The assertions were a replacement for some previous debugging code that checks conditions which no longer appear to be true.

Enable assertions during tests

---

src/aln.cpp
src/index.cpp
src/index.hpp
src/main.cpp
src/randstrobes.cpp
src/randstrobes.hpp
src/unused.cpp
tests/baseline-commit.txt

I’m working on reducing memory usage and need to make some refactorings along the way in order to encapsulate the index and some of the other data structures better, which will then make it easer to change the way the index is structured.
For example, I made `mers_index` private to ensure that it is accessed only through methods provided by the `StrobemerIndex` class. `KmerLookupEntry::count` also becomes a method. These "getter" methods are inlined by the compiler, so there’s no cost for this.
Lastly, commit bb4613176a46114832b785e4f935bfc1fc9b0a9f changes results: When sorting multiple `Hit`s, the current behavior is to sort them by count first and then by offset. I want to change this in a later commit so that a Hit doesn’t know where in the flat vector a strobemer is stored (that is, …

Refactor StrobemerIndex

---

src/pc.cpp

The unordered_map storing chunks to be written out to disk in the correct order needs to remove chunks that it wrote. 
Closes #180

Fix memory leak

---

src/aln.cpp
src/aln.hpp
tests/tests.cpp

This factors out a `has_shared_substring` function, adds a (failing) test for it and then fixes the issue.
The problem is that `read_seq.size() - k` becomes negative when the read is shorter than `k`, and
then the comparison is always true (because we compare to a `size_t`).

Fix crash in rescue_mate for short reads

---

src/main.cpp
src/version.hpp.in

When switching between branches, it often happens that CMake changes the CMAKE_BUILD_TYPE to Debug, which makes the resulting binary very slow. I have not been able to figure out, yet, why this is the case. I guess that somehow the CMakeCache.txt file is invalidated by changing the branches, and that this leads CMake to ignore the configured build type.
I would like to avoid that anyone benchmarks a strobealign binary compiled without optimizations, so until we’ve solved this, I’d like to print a fat warning when the build type is Debug.

Warn when binary was compiled without optimizations

---

CMakeLists.txt

I don’t know whether C++ 14 was chosen for a particular reason. If not, can we switch to C++ 17?
It has a couple of nice additions that I have refrained from using because we are still at C++ 14:
- Structured binding: https://en.cppreference.com/w/cpp/language/structured_binding
- string_view: https://en.cppreference.com/w/cpp/string/basic_string_view
- std::filesystem: https://en.cppreference.com/w/cpp/filesystem
- std::clamp https://en.cppreference.com/w/cpp/algorithm/clamp
Summary of C++ 17 changes: https://en.cppreference.com/w/cpp/17 That page also lists compiler support.

Switch to C++ 17

---

CMakeLists.txt
src/index.cpp
src/index.hpp
src/refs.cpp
src/refs.hpp
src/revcomp.hpp
src/tmpdir.hpp
tests/test_refs.cpp
tests/test_sam.cpp
tests/tests.cpp

Factoring out `read_`/`write_vector` should make it easier to continue work on #179 (where one of the suggestions was to write one of the vectors to disk to save memory).
I also added a `TemporaryDirectory` class that when instantiated creates a temporary directory in an appropriate place and deletes it automatically when the instance goes out of scope. This is here only used for testing, but for #179 would also be needed. BTW, this uses `std::filesystem`, which is from C++17.
Also, this splits the tests into multiple files.

Factor out read_/write_vector

---

ext/pdqsort/license.txt
ext/pdqsort/pdqsort.h
src/index.cpp
src/randstrobes.hpp
tests/baseline-commit.txt

This switches from `std::sort` to [pdqsort](https://github.com/orlp/pdqsort), which reduces the time needed for sorting the `ind_flat_vector` by roughly half.
I’m not sure whether this should be merged, but I wanted to at least document this experiment. Note that if I can finish my memory-saving ideas, then sorting won’t be as time-intensive anymore anyway, so the savings would be much lower.
To get a speedup at all, this requires that the `ind_flat_vector` entries (which are `MersIndexEntry` structs) are only compared by hash, not as it is currently done by hash, then reference position, then the "packed" attribute. Is there an assumption in the mapping/alignment code that requires that entries are not only sorted by hash, but also by position and the "packed" attribute?
Just simplifying …

Use pattern-defeating quicksort (pdqsort) to sort randstrobe hashes

---

CHANGES.md
ext/hyperloglog/hyperloglog.hpp
ext/hyperloglog/murmur3.h
src/aln.cpp
src/index.cpp
src/index.hpp
src/main.cpp
src/randstrobes.cpp
src/randstrobes.hpp
src/unused.cpp
tests/baseline-commit.txt
tests/tests.cpp

This is an extension of PR #179 (the first commits are the same). PR #179 reduced memory usage significantly when mapping using a pre-generated index, but increases memory usage at index generation time. The aim of this PR is to reduce memory usage even at index generation time.
It would have been possible to just add these commits to PR #179, but because this goes in a somewhat different direction and has different tradeoffs than what we discussed there, I’m opening a new PR.
The main downside of the method used here is that indexing time increases significantly (definitely more than 25%). I have thought about this a bit over the last weeks and am now at a point where we just need to discuss whether this is acceptable.
Memory usage is reduced to nearly the same level as when using the …

Memory reduction II

---

src/cmdline.cpp
src/cmdline.hpp
src/index.cpp
src/index.hpp
src/main.cpp

* Let `parse_command_line_arguments()` only return `CommandLineOptions`, not `mapping_params`. This better separates command-line parsing from the rest of the program. In particular, it allows to remove the `#include <aln.hpp>`, which will reduce necessary recompilations. (Command-line parsing should not need to recompile just because an alignment function changed signature.)
* Log total reference size, number of contigs and size of the maximum contig. This helps a little bit to double-check that one is working with the correct reference and may be valuable information when users post a bug report.
* Add `--create-index` as an alias for `-i` for symmetry with `--use-index`. Until/if we get a subcommand for indexing, I would suggest to promote this longer form in the documentation. It’s …

Refactoring, logging, add --create-index alias

---

src/aln.cpp
src/index.cpp
src/index.hpp
src/randstrobes.cpp
src/randstrobes.hpp

While doing this, I found that the "Total strobemers occur once" and "Fraction unique" statistics (only shown in in the debug log) weren’t computed correctly (broken by one of the recent PRs).

Get rid of some warnings

---

src/randstrobes.cpp

We don’t have to do the computations for the current syncmer if the syncmer position exceeds max_position.
No difference in runtime because the compiler does this optimization for us.

Simplify syncmer computation

---

CMakeLists.txt
src/aln.hpp
src/cmdline.cpp
src/cmdline.hpp
src/dumpstrobes.cpp
src/index.cpp
src/index.hpp
src/indexparameters.cpp
src/indexparameters.hpp
src/io.cpp
src/io.hpp
src/main.cpp
tests/tests.cpp

This does some refactoring and then ensures that the `-l` and `-u` command-line parameters are no longer ignored.
Fixes #199

Fix handling of -l and -u command-line parameters

---

src/aln.cpp
src/revcomp.hpp
tests/tests.cpp

I wrote a small test program to measure the differences in runtime. Reading in and reverse-complementing 1 million 150 bp reads takes 4.5 µs per read with the previous code and 2.2 µs per read with this version using a lookup table. Just parsing the FASTQ takes 1.2 µs, so reverse complementing time goes from 3.3 µs to 1.0 µs per read.
I tried to measure what the effect is on mapping time, but it makes nearly no difference (less than 1%). For the fruit fly dataset, mapping time per read went from something like 194.7±0.5µs before to 194.0±0.5 µs after the change.
It appears to me that reverse complementing is not responsible for any significant part of the mapping runtime. We currently have a caching mechanism for reverse complements, but I’m tempted to remove that and just *always* …

"Speed up" reverse-complementing

---

src/cmdline.cpp
tests/run.sh

New error message:
```
$ strobealign --create-index tests/phix.fasta
Error: The target read length needs to be known when generating an index.
Use -r to set it explicitly or let the program estimate it by providing at least one read file.
```

Require read length to be provided if --create-index is used

---

src/aln.cpp
src/aln.hpp
src/cmdline.cpp
src/cmdline.hpp
src/main.cpp
src/pc.cpp
src/sam.cpp
src/sam.hpp

This PR introduces a -U parameter to suppress the output of unmapped reads.
See https://github.com/ksahlin/strobealign/issues/206

Add commandline flag to suppress output of unmapped reads

---

src/dumpstrobes.cpp
src/index.cpp
src/index.hpp
src/indexparameters.cpp
src/indexparameters.hpp
tests/baseline-commit.txt
tests/tests.cpp

Closes #133.
We currently have the concept of an (actual) read length, which is either estimated from the input FASTQs or provided using the `-r` command-line option. This PR introduces the concept of a "canonical read length". The canonical read length is one of 50, 100, 150, 225, 325 and 400 (we choose the one that is closest to the actual read length) and represents one of the six pre-defined index parameter settings.
With this PR, all parameters are entirely based on the canonical read length only, which means that it can be re-used for datasets that have similar read lengths. This was almost the case before except that the `max_dist` parameter was computed from the actual read length. Commit 8ba1f937bbd14cfaad4c264346ffce3669cf3b49 changes this so that `max_dist` is computed from the …

Include read length in the index filename

---

README.md

No longer refer to pre-compiled binaries in installation instructions

---

src/aln.cpp
src/index.cpp
src/index.hpp
src/randstrobes.cpp
src/randstrobes.hpp
src/unused.cpp

I’ve been struggling a bit with the names of some of the types and variables. Whenever I haven’t looked at the code in `index.cpp/.h` for a week, I always need to re-read what `mers_vector`, `ind_mers_vector`, `ind_flat_vector`, `ReferenceMer` actually are.
I have a couple of preliminary suggestions for which I’ve added commits in this PR. I want to get some feedback before continuing, and also want to look at the code a bit to see how the new names would "feel". I’ll update this list if I make changes.
| now | suggested | comment |
|-|-|-|
| `ReferenceMer` | `RefRandstrobe` | location of a randstrobe on the reference (ref. index, position, strobe2_offset)|
| `MersIndexEntry` | `RefRandstrobeWithHash` | same as `RandstrobeOccurrence`, but stores also the hash|
| `kmer_lookup` | …

Suggestion to rename some key types

---

CHANGES.md
src/aln.hpp
src/cmdline.cpp
src/cmdline.hpp
src/main.cpp
src/pc.cpp
src/pc.hpp

I don’t know if this is your style, but I have added something similar to other programs, and I found it made the output just a tad friendlier.
During mapping, this progress indicator displays the number of mapped reads and the average (wall-clock) time per spent per read. 
Because the runtime per read fluctuates a bit in the beginning, the progress indicator is shown only after the first second to ensure we don’t have misleading numbers on the screen in case only a small number of reads were mapped.
Also, the progress indicator is only shown if the program is run interactively (when stderr is an actual terminal) to avoid cluttering log files when the user redirects stderr.
Totally fine with me if you don’t want this.
Animated preview: …

Show a progress indicator

---

tests/compare-baseline.sh
tests/download.sh

We’ve been using something like this in CI, but this is a version that can be run locally. I’ve been using this script for a while and found it very helpful. I run it manually whenever I made a nontrivial change that could change mapping results.

Script for comparing the current commit against the "baseline" commit

---

src/aln.cpp
src/nam.cpp
src/nam.hpp

- make `align_SE_secondary_hits` produce the same results as `align_SE` when called with max_secondary=1
- If max_secondary=1, handle that specially so that no sorting is done in order to avoid the overhead.
Note that max_secondary actually specifies the total number of alignments (#66). I’ll fix that separately.
`align_SE_secondary_hits` was and still is slightly buggy because it does not produce the same results as align_SE even when there are no secondary hits. I have explicitly *not* tried to fix that here, but only ensured that results are identical when `max_secondary=1`.
In my measurements, this is just as fast as before.
Closes #75

Remove align_SE and always call align_SE_secondary_hits

---

CMakeLists.txt
src/aln.hpp

I got complaints from valgrind and also the compiler has been warning about this for a while. This finally fixes that and also changes the compiler settings so that this type of problem becomes an error in the future (`-Werror=maybe-uninitialized`).

Correctly initialize AlignmentStatistics

---

src/aln.cpp
src/index.cpp
src/nam.cpp
src/nam.hpp
src/paf.cpp
src/paf.hpp
src/randstrobes.hpp
src/unused.cpp

The main change in this PR is to factor out a `merge_hits_into_nams` function that removes a nice chunk of duplicated code from `find_nams` and `find_nams_rescue`. Also:
* Rename `nam` to `Nam`
* Move `Hit` struct declaration into `find_nams_rescue` as it is used only there (and rename to `RescueHit`)
* Rename `hit` to `Hit`

Clean up NAMs a little bit

---

src/nam.cpp

PR #243 introduced a regression in that it made mapping a little bit slower because I accidentally passed `hits_per_ref` by by value to `merge_hits_into_nams()`. This changes it to pass by reference. With this, speed is as before.

Fix: Pass by reference

---

CHANGES.md
CMakeLists.txt
src/refs.cpp
tests/test_refs.cpp

This PR uses the zstr external library for this. It wraps zlib in a C++-compatible way so that we can use the FASTA parsing function unchanged.
While zstr can also read uncompressed input, it is a bit slower doing so than when using a regular std::ifstream. To avoid a performance regression, we use zstr::ifstream only if the input file name ends with `.gz` but fall back to std::ifstream otherwise.
Supersedes and closes #231

Support reading gzip-compressed references

---

src/main.cpp

Hi.
I am in the process of evaluating strobealign. I think it is very nice software.
By the way, the @PG tag in the SAM header, the spec says that the CL tag should show the command line options when run the analysis.
So I thought it was correct to modify it this way.
I would be happy if you could merge them.

mod to display cmdline options to sam header

---

CHANGES.md
README.md
src/aln.cpp
src/aln.hpp
src/cigar.cpp
src/cigar.hpp
src/cmdline.cpp
src/cmdline.hpp
src/main.cpp
src/pc.cpp
src/sam.cpp
src/sam.hpp
tests/run.sh
tests/test_aligner.cpp
tests/test_cigar.cpp
tests/test_sam.cpp

I needed to do some refactoring so that CIGARs are internally always represented as `Cigar` objects and only converted to their string representation at the very last moment when the alignments are serialized to SAM format. This makes it easy to optionally convert them to use `M` instead of `=`/`X` operations since the logic for that needs to be in only one place.
I chose `--m-op` as the name for the command-line option for now, but I’m not super happy with it. Bowtie2 and minimap2 have an `--eqx` switch and the opposite behavior: `M` by default and `=`/`X` is optional. Perhaps we should change the default as well for better compatibility? Also, that would avoid the spurious variant calling issue as long as htslib is not fixed.

Emit M instead of =/X CIGAR operations by default

---

tests/compare-baseline.sh

Otherwise, we compare non-M with M CIGAR strings when there are any other differences (different CIGAR strings alone do not cause two alignments to be considered different, which is why the tests still run fine even after switching the default to M CIGAR).

Use --eqx option when doing baseline comparison

---

src/aln.cpp
src/aln.hpp
src/main.cpp

Hi.
I was running Strobealign on a large file and noticed that it overflows when the number of reads exceeds the int limit.
n_reads are type inferred as signed int, but here it is better to use size_t.
I fixed this and would appreciate it if you could merge it.

fix overflow n_reads in show_progress_until_done

---

src/arguments.hpp
src/cmdline.hpp
src/exceptions.hpp
src/fastq.hpp
src/index.hpp
src/indexparameters.hpp
src/io.hpp
src/logger.hpp
src/pc.hpp
src/readlen.hpp
src/refs.hpp
src/revcomp.hpp
src/timer.hpp
src/tmpdir.hpp

This changes all include guards so that they consistently use `STROBEALIGN_xyz_HPP` for a file named `xyz.hpp`.

Make include guards consistent

---

.clang-format
CONTRIBUTING.md
README.md

By convention, guidelines for contributors are put into a file named `CONTRIBUTING.md` (I believe GitHub renders that specially). There are some web pages that have suggestions for how such a file could be structered, for example https://mozillascience.github.io/working-open-workshop/contributing/. I kept it small (and moved some text from the README) for now. I mainly wanted to have a place where I can put the code style guidelines so that I can refer to it in PRs.
This also adds the `.clang-format` file that is part of PR #266 just so it can be used manually for formatting new files as the style guide instructs.

Get started on documenting how to contribute

---

CHANGES.md
src/pc.cpp
src/pc.hpp
tests/test_input.cpp

A read named `read/1` followed by `read/2` should form a pair in the interleaved format. This matches the behaviour of `bwa mem -p` as well
closes #273
/cc #274

Ignore /1/2 suffix when matching interleaved reads

---

src/io.hpp

Building on MinGW gets the following error without this fix.
`io.hpp:21:5: error: 'uint64_t' was not declared in this scope`

Update io.hpp to fix MinGW build

---

src/python/strobealign.cpp
src/randstrobes.cpp
src/randstrobes.hpp

Hi!
I am wrapping `strobealign` and using it with another C library for processing reads, and my reads are stored in raw C-strings for ABI compatibility with the rest of the code. However, this means that I need to copy the reads to a `std::string` at every query, which can become expensive.
This PR updates `query_randstrobes` so that it uses a `std::string_view` rather than a `std::string`, avoiding unneeded copies. `std::string_view` was added in C++17, which is the minimum required version anyway. `std::string_view` can be obtained cheaply (without copy) from both a C++ `std::string` and an raw `const char*` pointer.

Use string views instead of strings when extracting query randstrobes

---

src/aln.cpp
tests/baseline-commit.txt

The iteration stopped a bit too early and therefore did not generate all possible l-mers.
`has_shared_subtring` is a heuristic used in `rescue_mate`. If query and reference do not share any substrings of length $l=\frac23k$, the read is marked as unmapped and no rescue is attempted.
This increases accuracy slightly for very short reads (50 bp).
* CHM13: 90.46475 → 90.48315
* fruit fly: 90.0643 → 90.0838
This changes how often rescue and alignment is done. For CHM13 (2x50):
* Total calls to ssw: 1972617 → 2003581
* Calls to ksw (rescue mode): 1257900 → 1288864
So probably runtime increases (the increase in ssw calls is much lower for the higher read lengths).
It appears to me that the behavior is a bug and should be fixed. If there’s a reason to not look at the last l-mers in the read, …

Fix has_shared_substring omitting some l-mers

---

src/aln.cpp
src/sam.cpp

This was a regression introduced in 51eab56e07dbbb88c67772e7cafa4b777646946f:
After `best_sam_aln = std::move(sam_aln)`, sam_aln should not be used, but we did use it when appending it to the alignments vector.
The  actual bugfix is in 6fb332684574a76569bbd29fcce0f787eb4aae51. This PR also sets SEQ and QUAL to `*` for secondary alignments as recommended by the SAM spec (see #212). (I verified that this is what BWA-MEM does as well.)
Closes #289
Closes #66

Fix secondary alignments not having CIGAR strings

---

CONTRIBUTING.md

I just noticed I forgot to bump the strobealign version for the Python bindings when releasing 0.10.0. I had also forgotten to make a release via the GitHub releases page. This PR adds a checklist for making a release.

Document how to make a release

---

CHANGES.md
ext/ssw/README.md
ext/ssw/sse2neon.h
ext/ssw/ssw.c
ext/ssw/ssw.h
ext/ssw/ssw_cpp.cpp
ext/ssw/ssw_cpp.h
src/aligner.cpp
tests/baseline-commit.txt

Obtained from
https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library
The previously included copy of SSW had been modified by adding a score_size parameter to Align(). This customization has been removed. This does not change behavior as the passed value passed was the default used by the library anyway.
This is an alternative to #295
Closes #294

Update SSW to v1.2.5

---

src/index.cpp
src/index.hpp
src/main.cpp

This is also part of #298, but I took the opportunity to make the index statistic logging a bit nicer, which I had wanted to do for a while.
Before:
```
Unique strobemers: 23324540
Total strobemers count: 26446802
Total strobemers occur once: 22560298
Fraction Unique: 0.97
Total strobemers highly abundant > 100: 1562
Total strobemers mid abundance (between 2-100): 762681
Total distinct strobemers stored: 23324540
```
After:
```
Index statistics
Total strobemers:          26446802
Unique strobemers:         23324540
1 occurrence:            22560298 ( 96.72%)
2..100 occurrences:        762681 (  3.27%)
>100 occurrences:            1562 (  0.01%)
```

Log index statistics in a nicer way

---

src/arguments.hpp
src/index.cpp
src/index.hpp

This improves handling of large references by hopefully crashing with a somewhat helpful error message (instead of just `std::length_error` or so).
Also, this limits the bits (`-b`) to the range 8..31. It may work up to 32, but this needs some further checking.
* Fix counting of randstrobes (this was just a 32 bit unsigned int and would therefore overflow on large references).
* Introduce a `bucket_index_t` type alias. The intention is for this to become a template parameter at a later stage, which can then be instantiated to be either a `uint32_t` or `uint64_t`.

Fail somewhat gracefully for too large references

---

src/randstrobes.cpp

See https://fastcompression.blogspot.com/2018/03/xxhash-for-small-keys-impressive-power.html
This speeds up index generation by ~3%.

Speed up index generation slightly by forcing inlining of XXH64

---

CHANGES.md
src/index.cpp
src/index.hpp
src/io.cpp
src/io.hpp
src/main.cpp
src/nam.cpp

(Marking as draft because this is untested.)
This unconditionally switches the bucket start indices from 32 to 64 bit. This makes strobealign work with more than $2^{32}$ strobemers, but also doubles memory usage of the index vector.
Closes #277
Closes #285

Make strobealign work with large references

---

src/index.cpp

On the first loop iteration, count is 0, so we would end up in the ++tot_mid_ab case.
Before:
```
Index statistics
Total strobemers:              1022
Distinct strobemers:           1022 (100.00%)
1 occurrence:                1022 (100.00%)
2..100 occurrences:             1 (  0.10%)
>100 occurrences:               0 (  0.00%)
```
After:
```
Index statistics
Total strobemers:              1022
Distinct strobemers:           1022 (100.00%)
1 occurrence:                1022 (100.00%)
2..100 occurrences:             0 (  0.00%)
>100 occurrences:               0 (  0.00%)
```

Fix off-by-one error in statistics

---

GitVersion.cmake
src/aln.cpp
src/dumpstrobes.cpp
src/index.cpp
src/index.hpp
src/indexparameters.cpp
src/indexparameters.hpp
src/main.cpp
src/python/strobealign.cpp
src/randstrobes.cpp
src/randstrobes.hpp
src/sam.cpp
src/sam.hpp
src/unused.cpp
tests/test_bindings.py
tests/test_sam.cpp
tests/tests.cpp

- Use a `std::vector<Syncmer>` instead of one vector for hashes and one for positions
- Rename `RandstrobeIterator2` to `RandstrobeGenerator` and add comments to explain what the difference is (to make it  clear that we need both at the moment)
- Tiny bugfix: Remove the `v` prefix from the version in the SAM PG header (only relevant when the version number is derived from a Git tag)
- Rename `alignment` struct to `Alignment`
- Move indexing parameters into separate `SyncmerParameters` and `RandstrobeParameters` structs

Various refactorings

---

tests/baseline-commit.txt

It refers to a nonexisting commit (probably arose because of rebasing)

Fix incorrect baseline commit hash

---

src/dumpstrobes.cpp
src/index.cpp

I found this useful for experiments: This adds a `--count` option to `dumpstrobes`, which will make it count all randstrobes (or syncmers if `--syncmers` is also provided).
This can also be used for benchmarking the `RandstrobeGenerator` and `SyncmerIterator` (only the overhead from reading the reference has to be subtracted from the measured runtime).

Add --count option to dumpstrobes command

---

CHANGES.md
src/index.cpp
src/index.hpp
tests/tests.cpp

This was surprisingly easy to implement with the new memory layout. However, this may not be the way to go and I’m opening this PR mainly to document the experiment.
The approach here still requires two passes over the references: The first pass counts the randstrobes for each reference and then uses that to compute the total needed length of the randstrobes vector (as before) and also at which offset in the vector the randstrobes for a contig need to be stored. Then the vector is filled in parallel from multiple worker threads. They use the offset to write into the correct position in the vector.
This works, but the speedup is only ~2X because the other steps of index generation (mainly sorting) is not parallel. Also, we still need the first randstrobe counting pass, whereas we could …

Compute strobemers in parallel

---

src/aln.cpp
tests/baseline-commit.txt

The first change is to [factor out an `is_proper_nam_pair()` function](https://github.com/ksahlin/strobealign/commit/23b245f391436baafbf28027a66e266099b36343). This changes behavior slightly as the code wasn’t identical at the two call sites. The condition for the distance was `a-b < 2000` in one case and `a-b < mu+10*sigma` in the other. The factored-out function uses the latter because taking the distribution into account seems to be the intended behavior.
The second change is to treat a pair of NAM as being a "proper pair" even if the query start positions are the same.
Both commits change accuracy slightly. The overall difference is as follows:
dataset | aed4738 | cd26078| difference
-|-|-|-
drosophila-50 | 90.1908 | 90.19065 | -0.0002
drosophila-100 | 92.3875 | 92.38865 | +0.0012 …

If R1 and R2 map to same position, treat them as proper pair

---

src/index.cpp
src/index.hpp
src/main.cpp
src/randstrobes.cpp

There was a race condition in updating `stats.tot_strobemer_count`, which led to the statistics being off. The strobemer count is already available from the first (counting-only) pass over the reference; we can just use that number instead.
This PR also includes a couple of refactoring commits.

Fix strobemer count statistics

---

src/aln.cpp

by ensuring that we compute at least two alignments even if the first that is found has edit distance 0.
Closes #293
Because I still need to test whether this actually fixes #293, I’m marking this as draft.

Avoid MAPQ=60 for single-end multimappers

---

src/nam.cpp

The intention of this parameter is to disallow hits that span too different lengths on the query compared to the reference.
The parameter has a bit of a misleading name because it is actually the *maximum* allowed difference. (This can come from some of my refactoring. Within the function, it represents the minimum observed difference so far. The value provided as argument is merely its initial value.)
But mainly, the parameter has no effect at all and just initializing it to `std::numeric_limits<int>::max()` leads to the same decisions being made. (I temporarily added some code tested this.)

Get rid of add_to_hits_per_ref() min_diff parameter

---

src/aln.cpp
src/index.hpp
src/nam.cpp
src/nam.hpp

I’m working my way through `align_PE` in order to understand how pairs are scored (so that I can work on #321). I came up with these refactorings/cleanups along the way.

Refactor align_PE

---

CHANGES.md
src/aln.cpp
tests/baseline-commit.txt

Closes #321.
The accuracy increases indeed a little bit.
dataset | main (4893484) | this PR (d723bb4) | difference
-|-|-|-
drosophila-50 | 90.189 | 90.1903 | +0.0013
drosophila-75 | 91.6441 | 91.64485 | +0.0007
drosophila-100 | 92.38785 | 92.38855 | +0.0007
drosophila-150 | 93.2112 | 93.21115 | -0.0001
drosophila-200 | 93.52085 | 93.52115 | +0.0003
drosophila-300 | 95.36085 | 95.36125 | +0.0004
drosophila-500 | 95.6936 | 95.6938 | +0.0002
maize-50 | 71.4703 | 71.47195 | +0.0016
maize-75 | 82.1255 | 82.12625 | +0.0007
maize-100 | 87.13175 | 87.1324 | +0.0007
maize-150 | 91.6731 | 91.67345 | +0.0003
maize-200 | 92.92045 | 92.9206 | +0.0002
maize-300 | 96.70835 | 96.70855 | +0.0002
maize-500 | 97.2899 | 97.29025 | +0.0003
CHM13-50 | 90.635 | 90.63505 | +0.0001
CHM13-75 | 92.5158 | 92.5161 | …

Penalize far apart pairs not more than as if they were two single ends

---

src/nam.cpp
src/nam.hpp
tests/baseline-commit.txt

`merge_hits_into_nams()` has two nested `for` loops that iterate over a single vector that contains both forward and reverse hits. In the inner loop, there’s a check to ensure that forward and reverse hits are never merged into NAMs.
We can instead keep forward and reverse hits in two different hash tables and work on them separately. This reduces the number of comparisons done in the inner loop. Interestingly, that change by itself doesn’t really reduce runtime. But what does reduce runtime is the subsequent commit that makes the `Hit` struct smaller by removing its `is_rc` attribute, which we no longer need.
Measurements on 100 bp single-end reads:
Reference | speedup
-|-
drosophila | ~2%
maize | ~9%
CHM13 | ~7%
rye | ~1%
I’ll post how accuracy changes tomorrow (so far, it looks as if …

Speed up NAM merging a bit

---

src/aligner.cpp
src/aligner.hpp
src/aln.cpp
src/aln.hpp
src/main.cpp
src/pc.cpp
src/pc.hpp

* Rename the last three classes/structs that did not have CamelCase names.
* Rename `get_alignment` to `extend_seed`
* etc.

More refactorings

---

src/indexparameters.cpp
src/indexparameters.hpp

There’s nothing inherently problematic with `w_min=0` and, as we see in #272, it even leads to higher accuracy for 50 bp reads.
This requires changing the `l` parameter from -4 to -3 for 50 bp reads if we want w_min to remain equal to 1 as before.

Allow w_min to be zero

---

src/randstrobes.cpp

Just a tiny refactoring to make it easier to change the way the syncmer hashes are combined into a single randstrobe hash.

Factor out a randstrobe_hash function

---

src/readlen.cpp
src/readlen.hpp

Closes #343
(This does not mean that it is actually possible to run CHM13 vs CHM13 in a reasonable amount of time, strobealign just doesn’t crash anymore before getting stuck.)

Fix read length estimation crash on chromosome-sized "reads"

---

src/hash.hpp
src/randstrobes.cpp

This function gives the same result as regular XXH64(), but with the difference that it only works on single 64-bit values, which makes it possible to reduce it to just a couple of lines; mostly the "bit mixing" part (functions finalize()/avalanche()) is left.
This performs a little bit better than calling the original function on an 8-byte slice because the compiler (at least GCC) does not fully inline the original function (finalize() remains a function call).
This speeds up index generation by a couple of percent: 163 are reduced to 159 seconds for CHM13.

Replace XXH64 with a simplified version

---

tests/run.sh

This just removes a minor inconvenience.

Do not require strobealign to be in PATH when running tests

---

src/nam.cpp

The nam_id started from 0 both for forward and reverse hits, which resulted in NAM ids being reused for different NAMs. This regression was introduced by commit 91f2223 and reduced accuracy.
This PR brings accuracy back to the expected levels (that is, higher than v0.11.0 due to tuned parameters).
I will need to re-run the parameter evaluation ...
See #345
for a couple of datasets
dataset           | v0.11.0 (93be0c2) | this PR (a290e7b) | difference
-|-|-|-
drosophila-50-pe  | 90.1908 | 90.499 | +0.3082
drosophila-100-pe | 92.3875 | 92.40435 | +0.0168
drosophila-150-pe | 93.21175 | 93.2124 | +0.0007
drosophila-200-pe | 93.5184 | 93.54275 | +0.0243
drosophila-300-pe | 95.3617 | 95.37225 | +0.0105
maize-50-pe       | 71.47185 | 72.9601 | +1.4882
maize-100-pe      | 87.13235 | 87.2842 | …

Fix: Avoid nam id collisions that reduce accuracy

---

src/dumpstrobes.cpp
src/index.cpp
src/index.hpp

With this, `dumpstrobes --seeds genome.fa` dumps the sorted randstrobes vector to standard output in a comma-separated format.
Columns:
- hash
- position
- reference index
- strobe 2 offset
I also had to move two functions in `index.cpp` into an anonymous namespace as otherwise the linker complains about a duplicate name (`count_randstrobes` exists twice).

Add dumpstrobes --seeds option for writing out the full seed vector

---

tests/baseline-commit.txt
tests/samdiff.py

This should ensure that the baseline comparison CI job doesn’t pass inadvertently as it did previously (see #361).
This also updates the baseline commit. To ensure we didn’t miss any changes in mapping results just because the samdiff script didn’t work, I ran it manually for each commit since the problem was introduced and can confirm that no other commit caused any changes.
Closes #361

Let baseline comparison fail if no reads were in the input

---

CHANGES.md
src/aln.cpp
src/sam.cpp
src/sam.hpp
tests/test_sam.cpp

This contains two changes: A bugfix and a change to the way MAPQ values are computed for single-end mapping.
First, the fix: There was a bug in MAPQ computation due to initializing `best_score` to -1000. In the first iteration, `min_mapq_diff` is updated in this way:
```c
min_mapq_diff = std::max(0, alignment.score - best_score);
```
With `best_score=-1000`, this is just `alignment.score + 1000`, so most of the time, `min_mapq_diff` ends up being something like 1600 or so for typical read lengths. This is then clamped to 60 in the output, which is probably the reason why we see MAPQ=60 most of the time.
Even with the fix, I didn’t understand what the code was doing. I think the *intention* is to use the second best score and relate it to the best score to compute the mapping quality, but …

Rework single-end MAPQ computation

---

tests/compare-baseline.sh

The use of `--eqx` was inconsistent so that `samdiff` would show that the CIGAR string has changed although it was just a change of which operators are used.
I will merge this as soon as the tests pass.

Do not use --eqx in baseline comparison script

---

CMakeLists.txt
src/aln.cpp
src/aln.hpp
src/insertsizedistribution.cpp
src/insertsizedistribution.hpp
src/pc.cpp
src/sam.hpp

This renames:
* `align_SE` → `align_single`
* `align_PE` → `align_paired`
* `align_SE_read` → `align_or_map_single`
* `align_PE_read` → `align_or_map_paired`
* `joint_nam_scores` → `nam_pairs` (since we now use the `NamPair` struct)
* `rescue_mate` → `rescue_align` (could never remember what it does differently from `rescue_read`)
* Rename `get_mapq` to `proper_pair_mapq` (since this is only used to compute MAPQ for uniquely mapping proper pairs)
Also, `InsertSizeDistribution` is moved to a separate file.
The main change is to factor out an output_aligned_pairs() function. The rescue_read() and align_paired() functions previously did two things:
- Compute a list of paired alignments
- Output them to SAM
When working on random alignment selection for #367, I noticed that the code …

Refactor aln.cpp

---

src/cmdline.cpp
src/cmdline.hpp
src/main.cpp
tests/run.sh

This is useful for our tests where we need output to be consistent even if the version number of the program changes.
The name of the option is chosen to be consistent with `samtools view`.

Add --no-PG option for not outputting the PG SAM header

---

CHANGES.md
CONTRIBUTING.md
src/aln.cpp
src/sam.cpp
src/sam.hpp

This is the number of alignments among which we (pseudo-randomly) choose one to output.
Is this useful? I thought I needed this for debugging, but then never actually looked at the numbers.
Regarding the name of the tag: The old `bwa aln` used `X0` for "Number of best hits", which I think is the same thing. There is a `H0` tag in the SAM specification with the description "Number of perfect hits", which could be something similar, but I could not find what it is actually intended to be used for, so I went with `X0`.
This requires #368 to be merged first.

With --details, add a SAM tag that shows the no. of identically scored best alignments

---

src/index.cpp

Previously 0th index was always skipped at the randstrobe start index. Also, count variable was initialized to 0, so we would end up in the ++tot_mid_ab case, even if this was a single occurrence.

Fix first index of randstrobe start index to be always the 0th randstrobe

---

CHANGES.md
README.md
src/indexparameters.cpp

Also, remove canonical read length 300 because after changing the parameters, 250 and 300 were using the same.

Use optimized indexing parameters

---

src/sam.cpp

This follows recomended best practice: "No alignments should be assigned mapping quality 255." according to the SAM specification.
Using MAPQ=0 follows what BWA-MEM does for secondary alignments.
Closes #212

Set MAPQ=0 for secondary alignments

---

src/cmdline.cpp

This is embarrassing.
`grep` tells me that this is the only occurrence.
Closes #383

Fix misspelled "strobealign"

---

src/aln.cpp

Commit 1fe3e34 made a buggy refactoring: I thought that the `score` attribute of `NamPair` objects is the same as the sum of the scores of the two constituent NAMs. But that is incorrect: The `score` is actually the sum of the `n_hits`.
This PR fixes that and renames `NamPair::score` to `NamPair::n_hits` to eliminate this confusion.

Fix drop in mapping-only accuracy

---

.github/workflows/ci.yml
tests/compare-baseline.sh

Do not let GitHub Actions do the work, but rely on the baseline comparison script. Only ensure caches are filled before starting it.
This reduces a little bit of code in the GitHub Actions workflow file (reduces essentially duplicate code).
We will only be able to see whether retrieving the cached baseline file works correctly on the next PR.

Simplify baseline comparison on CI

---

src/main.cpp
src/randstrobes.hpp

Right now, strobealign only supports up to 2²⁴ sequences. If the user tries more, it would silently accept it, but later crash.

Explicit error if too many sequences are used

---

src/randstrobes.hpp

By ensuring randstrobes are sorted by all their fields.
I thought that the comparison function I added in #386 (commit 2e4ff9500e68d6e465735dd276d362cf71851dcd) was good enough, but now that I ran on some other datasets that I hadn’t used for testing previously, it became apparent that that’s not the case because I was getting non-reproducible results.
This slows down index creation again a little bit (now takes ~61s instead of ~60s for CHM13), but it’s still a lot faster than before parallel sorting.

Make index creation deterministic

---

pyproject.toml
src/python/strobealign.cpp
tests/test_bindings.py

It currently returns an empty list (regression introduced in 59b4d04b2234a6b28624418f4cfafe666bfb0348)

Fix StrobemerIndex.find() in Python bindings

---

CHANGES.md
CMakeLists.txt
CONTRIBUTING.md
README.md
setup.py

- Streamline "Usage" section in README
- Make the three output modes (alignment, mapping only, aemb) clearer
- Add `--aemb` to changelog
- Bump version to 0.13.0

Version 0.13.0

---

CHANGES.md
src/cmdline.cpp
src/cmdline.hpp
src/main.cpp

Also, adjusted logging output to make it more obvious how many threads are used (and which mode). Example:
```
...
Total time indexing: 3.79 s
Processing paired-end reads in mapping-only mode using 1 worker thread
Mapped         1.00 M reads @    11.02 us/read
Done!
```
Other example messages:
```
Processing single-end reads in abundance estimation mode using 4 worker threads
...
Processing single-end reads using 4 worker threads
```
Closes #401

Set default number of threads to 1

---

src/main.cpp

Previously, output would always be sent to stdout, even when `-o` was provided.

Make --aemb work with -o

---

src/nam.cpp

It would be more correct to convert all start and end coordinates on query and reference to unsigned, but this is a much smaller change and should do for now.
```
warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
99 |             if (h.query_start > prev_q_start + k) {
|                 ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
```

Get rid of the last compiler warning

---

tests/run.sh

Gzip files support being concatenated. We need to ensure that strobealign can deal with this.

Test multi-block gzip files as input

---

src/python/strobealign.cpp

Nanobind changelog
(https://nanobind.readthedocs.io/en/latest/changelog.html#version-2-0-0-may-23-2024):
> The nb::enum_<T>() binding declaration is now a wrapper that creates either
> a enum.Enum or enum.IntEnum-derived type. Previously, nanobind relied on a
> custom enumeration base class that was a frequent source of friction for
> users.
>
> This change may break code that casts entries to integers, which now only
> works for arithmetic (enum.IntEnum-derived) enumerations.

Make Python bindings work with nanobind 2+

---

CMakeLists.txt
CONTRIBUTING.md
src/aln.cpp
src/cmdline.hpp

If `cmake` is run with `-DTRACE=ON`, then some `#ifdef`s become active that make strobealign print the list of found NAMs for each query.
I find myself adding this type of output quite often for debugging purposes, and think it would be nice to have this as part of the code, disabled by default, but easily enabled.
`CHUNK_SIZE` is forced to 1 when tracing is on to ensure that SAM/PAF output comes right after the corresponding tracing output. (Otherwise you get the tracing output for all queries within one chunk follewd by all the SAM/PAF output for all queries in the chunk.)

Add a debugging compilation option for showing list of NAMs

---

.github/workflows/ci.yml
CHANGES.md
CMakeLists.txt
README.md
src/fastq.cpp
src/fastq.hpp
src/iowrap.cpp
src/iowrap.hpp
src/main.cpp
src/pc.hpp

This is a continuation of #269 where I fixed the things I commented on.
I will need to re-measure memory usage. At some point, it was higher than previously, but that seems to be fixed now.
As intended, runtime improves slightly.
Marked as draft because two issues remain:

Decompress with ISA-L

---

CMakeLists.txt

I would like to suggest no longer compiling the `unused.cpp` file by default for a couple of reasons:
- Because it includes some header files, it takes extra effort to make it compilable if those header files change.
- While building, many warning messages are printed just for unused.cpp while for strobealign itself almost all warnings have been eliminated. This makes it harder to see whether a change introduces a new warning.
- It takes extra time to compile (just a couple of seconds each time, but it adds up).
This PR removes the file as a target from `CMakeLists.txt` so that it no longer gets compiled. I haven’t deleted the file itself for now.

Do not compile unused.cpp

---

README.md

(I tend to see questions in the issue tracker as hints where the documentation needs to be improved.)
See #440

Explain that all best mapping locations are counted with --aemb, contrast to alignment mode

---

src/index.cpp
src/index.hpp

Fixed several issues in the index statistics
- Since `get_count(size_t position)` counts the seed abundance starting from the argument position, `get_count` is now used with the first occurrence position 
- Fixed median seed length
- Clarified statistics text

Fix index construction statistics

---

CONTRIBUTING.md
src/aln.cpp
src/aln.hpp
src/main.cpp
src/nam.cpp
src/nam.hpp
src/python/strobealign.cpp
src/sam.cpp
src/sam.hpp
src/statistics.hpp

With this, some extra diagnostics are printed when verbose output is requested with `-v`:
```
Number of reads: 1000000
Number of non-rescue hits: 25160733 total. Per read: 25.16
Number of non-rescue NAMs: 27321159 total. Per read: 27.32
Number of rescue hits: 583028 total. Per rescue attempt: 23.07
Number of rescue NAMs: 11457402 total. Per rescue attempt: 453.27
```
I’m using this to figure out why the multi-context seeds branch makes strobealign slower.

Add some diagnostics

---

src/randstrobes.cpp
tests/tests.cpp

... and add tests for RandstrobeIterator/-Generator.
Split out from #426.

Add make_randstrobe function

---

src/arguments.hpp
src/cmdline.cpp
src/cmdline.hpp
src/dumpstrobes.cpp
src/index.cpp
src/indexparameters.cpp
src/indexparameters.hpp
src/main.cpp
src/randstrobes.cpp
src/randstrobes.hpp

Again, this is split out from #426.
This adds the `--aux-len` command-line parameter and changes the hash function. Multi-context seeds are not used during lookup. That is, while the contents of the index change, there should be no changes in output (and there aren’t as far as I can tell).
Interestingly, this version of the hash function makes strobealign slightly faster, about 1-4% depending on the dataset. I’m not sure what is going on, but I’ll take it.

Switch to multi-context seeds hash function

---

CHANGES.md
CMakeLists.txt
setup.py

I think this is a good time for a release, with the ISA-L improvements and just after we switched to multi-context ~~seeds~~ hashes (which gives a slight speedup), but before actually using them.
(Edited)

Prepare release: Bump version to 0.14.0

---

src/aln.cpp
src/nam.cpp
src/nam.hpp
src/paf.cpp
src/python/strobealign.cpp

We use the term "hit" both for
- a query strobemer successfully looked up in the index
- a locus on the query paired with a locus on the reference (this type of hit is merged into NAMs)
I think choosing the name for the latter to be "match" makes sense because the M in NAM stands for "match". That is, we can then say that we merge multiple overlapping matches into non-overlapping, approximate matches (=NAMs).
The flow would then be: hit -> match -> NAM.
Marking as draft because this should only be merged after #426 as it will otherwise cause conflicts.

Rename Hit struct to Match

---

CHANGES.md
src/index.cpp
src/index.hpp
src/nam.cpp
src/python/strobealign.cpp
src/randstrobes.cpp
src/randstrobes.hpp

Mainly, this removes one of the currently duplicated `StrobemerIndex::find*()` functions.
Instead, have a common function that has a parameter which tells it how many bit of the hash to ignore (0 for finding a full hash and aux_len for a partial one).
Same for `get_count()`.

Multi-context seeds refactoring and docs

---

src/aln.cpp
src/main.cpp
src/statistics.hpp

With `-v`, this reports the number of generated randstrobes in total and per read.

Report number of generated randstrobes

---

CHANGES.md
README.md
src/cmdline.cpp
src/nam.cpp
tests/baseline-commit.txt

Credit for this idea goes to @Itolstoganov.
PR #472 changes the index so that the first syncmer is always chosen as the base. This improves accuracy in MCS, but reduces mapping rate (and thus accuracy) in non-MCS mode. Apparently, some reads with many errors no longer get any hits at all.
However, we can easily detect when a query doesn’t get any hits and then - even if MCS isn’t explicitly enabled - just use the method we already have of looking up partial seeds, as a different kind of MCS rescue.
To be clear, only using partial seeds when no regular hits can be found was an idea by @Itolstoganov.
This actually works *much better* than I would have expected: Both accuracy and speed get improve!
Details below.

Rescue using partial hits, even in non-MCS mode

---

src/aln.cpp
src/nam.cpp
src/nam.hpp
src/paf.cpp
src/python/strobealign.cpp
src/randstrobes.cpp
src/randstrobes.hpp
src/sam.cpp
src/sam.hpp
src/unused.cpp
tests/test_sam.cpp

I didn’t get anywhere with the actual change I wanted to make (related to MCS), but here’s at least some refactoring I did along the way. The biggest change is factoring out a `get_nams()` function that contains some code previously duplicated between `align_or_map_single` and
`align_or_map_paired`.

Some refactoring

---

README.md

A colleague who is testing strobealign asked me about this.

Clarify that PAF omits unmapped reads

---

src/aligner.cpp
src/aligner.hpp
src/aln.cpp
src/main.cpp
src/statistics.hpp

Mostly a small logging cleanup.
Before:
```
Number of reads: 1
Number of randstrobes: 46 total. Per read: 46.00
Number of non-rescue hits: 19 total. Per read: 19.00
Number of non-rescue NAMs: 8 total. Per read: 8.00
Number of rescue hits: 0 total. Per rescue attempt: -nan
Number of rescue NAMs: 0 total. Per rescue attempt: -nan
```
After:
```
Number of reads:                          1
Number of randstrobes:                   46  Per read:   46.00
Number of non-rescue hits:               19  Per read:   19.00
Number of non-rescue NAMs:                8  Per read:    8.00
Number of NAM rescue attempts:            0
Number of rescue hits:                    0  Per rescue attempt:    -nan
Number of rescue NAMs:                    0  Per rescue attempt:    -nan
```

Logging cleanup and some minor refactoring

---

src/index.cpp
src/index.hpp
tests/tests.cpp

Otherwise, on a very short reference (size 0 or so), pick_bits returns 31 and creates a huge randstrobe_starts vector.
Closes #487

Ensure pick_bits does not take the logarithm of 0

---

CONTRIBUTING.md
src/nam.cpp
src/nam.hpp
src/python/strobealign.cpp
tests/test_bindings.py

The Python bindings were a bit out of date. Previously, strobealign had a single `find_nams` function, but this was split up into `find_hits`, `hits_to_matches` and `merge_matches_into_nams`. The bindings only had the first function. This PR adds the other two.

Extend Python bindings

---

CHANGES.md
src/index.hpp

`find_partial` and `find_full` can return the special value `end()`, which indicates that the hash was not found. We need to check for this value before using it as an index into the randstrobes vector.
This fixes a crash on macOS.

Fix out-of-bounds memory access

---

.clang-format

We’re not actually using clang-format, yet (PR #266 is unmerged), but there is a `.clang-format` file in the repository already. This updates that file so that anyone who wants to format new files with it (such as the upcoming `chain.cpp`) can use it and get it formatted the way we would like it.

Tune clang-format settings a bit

---

CMakeLists.txt
src/aln.cpp
src/cmdline.cpp
src/cmdline.hpp
src/logger.hpp
src/main.cpp

To get highly verbose trace output (which prints all NAMs found for each read), we previously needed to re-run cmake with `-DTRACE` and then re-compile strobealign.
This PR adds a command-line option `--trace` instead (it’s currently hidden in the `--help` output), which is a lot more convenient.
I originally made this a compile-time option because I wanted to avoid the runtime overhead when tracing is not requested, but this doesn’t make sense because the overhead should be just a couple of cycles per query. (I was thinking of Python, where this is more relevant.)

Add a --trace command-line option

---

CMakeLists.txt
src/aln.cpp
src/aln.hpp
src/chain.cpp
src/cmdline.cpp
src/cmdline.hpp
src/main.cpp
src/mcsstrategy.cpp
src/mcsstrategy.hpp
src/nam.cpp
src/nam.hpp
src/python/strobealign.cpp
tests/run.sh
tests/test_bindings.py

This changes how the command-line option `--mcs` works: Instead of it being a flag that is either set or not (`--mcs` given or not), this is now an option that accepts one of four values:
- `--mcs=rescue` is the same as what we do now (do full lookup for each strobemer and then if there are no hits for a query, try partial lookup)
- `--mcs=always` is the same as what we currently do when `--mcs` is given: Do a full lookup for each strobemer and try partial lookup if that did not generate a hit.
- `--mcs=off` is new and turns off MCS, that is, it makes strobealign always do a full lookup.
- `--mcs=first-strobe` is also new and forces strobealign to only do partial lookups
This allows us to use a single strobealign binary for the benchmarks that then just gets run with different …

Add command-line option for setting the MCS strategy

---

src/cmdline.cpp
src/cmdline.hpp
src/main.cpp

This adds the hidden command-line option `--ithreads`, which allows to set a different number of threads for indexing than for mapping/alignment.
This is mainly useful for debugging, for example, when also `--trace` is used: For `--trace`, one should use `--threads 1` because the output of multiple threads will otherwise interleave and not be useful. However, because indexing then also happens with just one thread, it can be a bit annoying to have to wait for that to happen. `--ithreads` solves this.

Add option for setting the number of indexing threads

---

src/randstrobes.hpp

Depending on the toolchain, it seems that the `<array>` header sometimes is already included some other way, which is why this was not noticed before.

Add a missing include

---

src/aln.cpp
src/chain.cpp
src/hits.cpp
src/hits.hpp
src/main.cpp
src/nam.cpp
src/python/strobealign.cpp
src/statistics.hpp
tests/compare-baseline.sh

During our last meeting, a question about the number of partial hits came up that was hard to answer with our current log output.
This PR adds more detailed statistics (within `find_hits`) that track all six possible outcomes when looking up randstrobes in the index. When looking up a full randstrobe, we have three different outcomes:
- The randstrobe was found but filtered (because it is repetitive)
- The randstrobe was found and not filtered
- The randstrobe was not found
If the randstrobe was not found and when using MCS, we also do partial lookups and again have the same three cases (found but filtered, found and not filtered, not found).
Only the non-rescue lookups are reported in this way. Since rescue lookups work a bit differently, I haven’t changed their numbers, only moved where …

More detailed randstrobe lookup statistics

---

src/cmdline.cpp
src/cmdline.hpp
src/main.cpp
src/pc.cpp
src/pc.hpp

Let chunk size be in terms of nucleotides, not number of reads
Note that there’s a hidden command-line option `--chunk-size`. This is now re-intepreted as meaning the number of *nucleotides* in a chunk. This way, there are fewer reads in a chunk if the reads are longer.
This avoids the problem that we do not use all input threads for small input
datasets with long reads (if the input had 50000 reads, we would use at most
5 threads, for example).
Experiments suggest that the chunk size can be relatively small without
adding too much overhead. Even for 100 nt reads and a chunk size of 1 read,
mapping is just a couple of percent slower than with bigger chunk sizes.

Adjust chunk size depending on read length
