- src/main.cpp
This is a mish-mash of various things that refactor and simplify the code. No functional changes.
> Refactor and simplify

- src/index.hpp
- src/main.cpp
This simplifies the loop in which logging_variables for each thread are
summed up.
> Implement operator+= for logging_variables

- src/main.cpp
- tests/run.sh
This moves index creation into a separate function. There’s more to be done, for example, I think the index should perhaps become a class, but I need to understand the code better before I can do that.
@johan-gson If you want, I think you could start looking into how to write the index to disk after this is merged.
> Factor out `create_index()` (and some other changes)

- src/index.cpp
Am I thinking correctly? The `if (i + w_max < nr_hashes)` a couple of lines earlier already ensures that `(nr_hashes <= i + w_max)` is true if we get to the `else`.
> Remove expression that is always true

- src/aln.cpp
Add a couple of const and remove some duplicate code
> Refactor get_best_scoring_pair

- src/aln.cpp
- src/unused.cpp
- Move unusesd code to `unused.cpp`
- Remove unused parameters
- Make nearly all parameters const
> Clean up find_nams and find_nams_rescue a bit

- .github/workflows/ci.yml
- src/aln.cpp
- src/unused.cpp
> Fix compilation on macOS and run tests on macOS

- src/aln.cpp
- src/timer.hpp
This introduces a simple `Timer` class that simplifies some of the repetitive time measurement code. I only made the necessary changes in `aln.cpp` an not in `main.cpp` and `index.cpp` because I did not want to cause merge conflicts in the other open PRs.
> Introduce a Timer class and use it

- src/index.cpp
- src/index.hpp
- src/main.cpp
I tried to address #95 but the Github checks fail on me. This is weird since I didn't touch the code in aln.cpp at all.
> Adding IndexCreationStatistics struct to address #95

- src/aln.cpp
Simplifiies a loop that is written out twice. Once it is run on `hits_fw` and once on `hits_rc`. This adds an outer loop that iterates over `hits_fw` and `hits_rc`.
> Deduplicate some code in find_nams_rescue

- src/aln.cpp
The second commit de-dents lots of code in `align_PE` that is in an else block after an early return.
> Factor out joint_mapq_from_high_scores()

- CHANGES.md
- README.md
Only the changes since v0.7.0 are included.
> Add a changelog and fill it

- .github/workflows/ci.yml
This should save ca 50 seconds on CI when there is a cache hit
> Cache the baseline BAM

- .github/workflows/ci.yml
- src/refs.cpp
- src/refs.hpp
- src/sam.cpp
- src/sam.hpp
- tests/tests.cpp
This fixes the SAM validation issue #148
> Fix invalid alignment starts

- README.md
Not sure if you want this, but I just found that video and thought it gave a really good overview in a short amount of time.
> Add link to RECOMB-Seq video to README

- README.md
> Describe how to use index files

- src/index.cpp
I had originally included this as part of PR #195, but this can be done independently.
> Store file format version in the .sti file and check it when reading

- src/main.cpp
This may be helpful in the future ...
> Show whether AVX2 is enabled in debug log

- CHANGES.md
The last remaining to do before the release.
> Changelog for v0.8.0

- README.md
> Fix Bioconda install link

- README.md
@luispedro Here’s a description of how to run one of the testing scripts.
> Add a "Contributing" section to the README

- src/randstrobes.cpp
I just understood why `randstrobes_query` re-uses the syncmers that it computed for forward sequence for the reverse complement, and why it does not do the same thing for the randstrobes, so I would like to document it. This cleans up the function a little bit and adds a couple of comments.
> Clean up and comment randstrobes_query

- src/aln.cpp
> Fix timing of NAM sorting

- CHANGES.md
- src/index.cpp
- src/index.hpp
- src/nam.cpp
- src/python/strobealign.cpp
- src/randstrobes.cpp
- src/randstrobes.hpp
- src/unused.cpp
- tests/baseline-commit.txt
> Some touchups after #278

- src/indexparameters.cpp
> Slightly improve accuracy for read length 250

- CHANGES.md
- src/aln.cpp
- tests/baseline-commit.txt
Continues work started in #364
I have not done any measurements, will do so later. 
Closes #359
> Random paired-end alignment selection

- CHANGES.md
- CMakeLists.txt
- ext/README.md
- ext/zstr/CMakeLists.txt
- ext/zstr/LICENSE
- ext/zstr/README.org
- ext/zstr/src/strict_fstream.hpp
- ext/zstr/src/zstr.hpp
This way, the strobealign sources are more self-contained and it should not be necessary to have internet access at build time.
> Vendor zstr instead of fetching it from Git at build time

- CHANGES.md
- README.md
- src/indexparameters.cpp
> Introduce canonical read length 75

- README.md
> Add samtools to conda install command

- src/nam.cpp
This took me a while to understand. I think it’s worth pointing this out directly in the code.
> Doc: Partial hashes lead to multiple identical matches

- src/randstrobes.hpp
- tests/test_randstrobes.cpp
> Test: SyncmerIterator returns canonical syncmers

- CHANGES.md
- src/refs.cpp
- tests/test_refs.cpp
> Be less strict when verifying contig identifiers
